project:
  type: website
  output-dir: docs/
  render:
    - "*.qmd"
    - "projects/*.qmd"
    - "data-projects/*.qmd"
    - "data-projects/health_indicators/*.qmd"
    - "publications/*.qmd"
    - "talks/*.qmd"
    - "photos/photos.qmd"
    - "!posts_draft/"
    - "!_en/"
    - "!_en/**"

lang: pt-BR

website:
  favicon: logo.png
  title: "Raphael Saldanha"
  site-url: https://rfsaldanha.github.io
  page-navigation: true
  back-to-top-navigation: true
  google-analytics: "G-2M7VLSRDCB"
  page-footer:
    background: light
    left: "Copyright 2024, Raphael Saldanha"
    right:
      - icon: github
        href: https://github.com/rfsaldanha
      - icon: mastodon
        href: https://fosstodon.org/@rfsaldanha
  navbar:
    logo: logo.png
    logo-alt: Raphael Saldanha
    search: true
    right:
      - text: "CV"
        href: cv.qmd
      - text: "Projetos"
        href: projects.qmd
      - text: "Pacotes & Código"
        href: code.qmd
      - text: "Dados"
        href: data.qmd
      - text: "Publicações"
        href: publications.qmd
      - text: "Talks"
        href: talks.qmd
      - text: "Fotos"
        href: photos/photos.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "English"
        href: en/
      - icon: rss
        href: blog.xml

format:
  html:
    theme:
      - styles.scss
    mainfont: Nunito
    toc: true

editor: visual
