---
title: "CV"
---

## Informações gerais

-   Nome completo: Raphael de Freitas Saldanha

-   Data de nascimento: 18 de abril de 1985

-   Idiomas: português, inglês

## Experiência

-   2025 - presente. **Pesquisador permanente** na Fiocruz -- Fundação Oswaldo Cruz.

-   2024 - presente. **Fellow researcher** na Pasteur Network.

-   2025 - 2025. **Assistente de pesquisa** na Fiocruz -- Fundação Oswaldo Cruz.

-   2023 - 2024. **Pesquisador de pós-doutorado** no Inria e no LNCC.

-   2021 - 2023. **Assistente de pesquisa** na Fiocruz -- Fundação Oswaldo Cruz.

## Formação

-   2018 - 2021. **Doutorado** na Fiocruz, PPGICS. Informação e Comunicação em Saúde. *Aplicações de ciência de dados para a saúde pública*.

-   2015 - 2017. **Mestrado** na UFJF - PPGSC em Saúde Coletiva. *Violência no trânsito e crescimento econômico: uma análise de econometria espacial*.

-   2008 - 2009. **Especialização** na UFJF. Métodos Estatísticos Computacionais. *Violência no trânsito e lei seca: um estudo de avaliação de política pública*.

-   2003 - 2007. **Bacharelado** na UFJF - ICHL-DG. Geografia. *Proposta de regionalização para a cidade de Juiz de Fora com base nos dados do Censo 2000*.

## Interesses acadêmicos

### Áreas

-   Clima e saúde
-   Meio ambiente e poluição do ar
-   Geografia da saúde
-   Saúde digital

### Ciência de dados

-   R
-   Aprendizado de máquina
-   tidyverse, tidymodels
-   Aplicações Shiny
-   Quarto
-   duckdb
-   ElasticSearch

### Geoprocessamento

-   QGIS
-   ESRI ArcGIS
-   GeoServer

### Outras tecnologias

-   Gephi
-   LaTeX
-   Linux
-   MacOS

## Experiência profissional e docente

-   2024 - presente. Editor associado da RECIIS.

-   2021 - 2022. Assistente de pesquisa na Fiocruz, IOC, Laboratório Lathema (ArboAlvo).

-   2017 - 2018. Assistente de pesquisa no IRD, Maison de la Télédétection (Montpellier, França).

-   2017 - presente. Docente em oficinas de Introdução à Econometria Espacial com R.

-   2013. Estágio docente em Metodologia Científica na UFJF, CRITT.

-   2005 - 2016. Analista de geoprocessamento e estatística na Plangeo.

-   2012 - 2013. Supervisor de educação a distância em Estatística no curso de Gestão Pública.

-   2012. Aprovado em concurso para professor substituto de Cartografia Temática.

-   2011. Tutor a distância de Estatística Empresarial (Curso de Administração Pública à Distância -- PNAP), UFJF.

-   2010. Professor de Tecnologias para Planejamento Ambiental, FAFISM.

## Formação complementar

-   2023. Nature-based solutions for tackling global health challenges. Heidelberg Institute of Global Health, HIGH, Alemanha.

-   2022. Algorithms and Programming Methods for Big Data. Laboratório Nacional de Computação Científica (LNCC, Brasil).

-   2023. VII Escola Avançada em Big Data Analytics (USP, Brasil).

-   2022. Public Health Disparities Geocoding Project 2.0. Harvard School of Public Health.

-   2022. Developing the SIR Model. Imperial College (Coursera).

-   2022. Machine Learning methods with R, Curso-R.

-   2021. R Deploy methods, Curso-R.

-   2021. QBA/On-line - Sensibilização em Gestão da Qualidade, Biossegurança e Ambiente, Fiocruz.

-   2020. Comunicação, Mídia e Saúde em Contexto de Emergências Sanitárias, UFAL.

-   2018. Anthropological and Historical Approaches of Visualising Epidemics, COC, Fiocruz.

-   2018. Information Visualization, Foundations and Applied Perception, NYU Tandon School of Engineering (Coursera).

-   2017. Practical Machine Learning, Johns Hopkins University (Coursera).

-   2016. Harvard - Brazil Collaborative Public Health Course, Harvard School of Public Health.

-   2015. Introduction to Big Data, University of California, San Diego (Coursera).

-   2011. Geoestatística com o uso do R, UFJF.

-   2007. Oficina em modelagem para estudos longitudinais, UFJF.

-   2007. Geomarketing - Conceitos e aplicações, Centro Universitário Senac.

-   2004. Geografia e movimentos sociais, A América Latina, AGB.

-   2003. Introdução à Gestão Ambiental Urbana, UFJF.

-   2003. Flash Mx, CRITT, UFJF.

## Hobbies

-   Fotografia

-   Ciclismo
