---
title: "Climate change and health impacts webinar"
author: "CCMI"
date: 2023-11-21
categories: [webinar, online, free, 2023]
---

## Description

Join the CCMI project for an insightful webinar on 21 November 2023: 11:00-12:00 CET exploring the latest developments and opportunities in assessing the links between climate change and health. The webinar will also explore the co-benefits that ambitious climate action, together with mitigation and adaptation measures can bring on human health. Prominent speakers from the climate modelling and health space will join the discussion. Register below and reserve your spot! Confirmed speakers include: Vicky Pollard, DG CLIMA; Ana M. Vicedo Cabrera, University of Bern; Thessa Beck, Barcelona Institute for Global Health; Andrea Bassi, IISD and Stellenbosch University, South Africa and Shreya Some, Asian Institute of Technology.

## Links

-   <https://ec.europa.eu/newsroom/clima/items/807552/en>
-   Slides: <http://www.climatechangemodelling.com/Webinars>
