---
title: "European Congress of Clinical Microbiology and Infectious Diseases 2024"
author: "ECCMID"
date: 2024-04-27
categories: [congress, hybrid, paid, 2024]
---

## Description

ECCMID 2024 will follow the successful format introduced in 2022, offering a comprehensive hybrid congress. While we encourage the majority of our faculty, abstract presenters, and attendees, to participate on-site and benefit from the scientific, educational and networking experiences, provided by ECCMID, our seamless hybrid solution allows remote attendance for those unable to travel for any reason. Whether you come and join us in Barcelona, Spain or sign in online from your living room or office, you will be able to fully enjoy what ECCMID 2024 has to offer.

## Climate change and the spectrum of infectious consequences (2h Symposium)

-   Ancient viruses revived from permafrost. Jean-Michel Claverie (Marseille, France)
-   Monitoring the effects of climate change on the distribution of infectious diseases. Rachel Lowe (Barcelona, Spain)
-   Climate change and AMR: challenges in a moving world. Sabiha Essack (Durban, South Africa)
-   Climate change and cholera. TBA

Co-organised with: Deutsche Gesellschaft für Infektiologie, ESCMID Professional Affairs Subcommittee, ESCMID Study Group for Infections in Travellers and Migrants (ESGITM), Trainee Association of ESCMID (TAE) Steering Committee.

## Links

-   <https://www.eccmid.org/>
