---
title: "Connecting Health and Climate Change Conference"
author: "ENBEL"
date: 2023-10-11
categories: [conference, hybrid, free, 2023]
---

## Description

Climate change is already impacting health in multiple ways and is undermining determinants for good health, such as clean air and water, food, safe shelter, and economic opportunities. The transdisciplinary conference on Connecting Health and Climate Change brings together researchers, experts, policy makers, and NGO and private sector representatives, from all career stages. It provides an arena to present research findings and discuss climate change effects on health, adaptation, societal consequences,and opportunities for climate resilient development.

The hybrid conference is organized by ENBEL - Enhancing Belmont Research Action to support EU policy making on climate change and health. ENBEL coordinates a network of international health and climate researchers under the Belmont Forum’s Collaborative Research Action on Climate, Environment and Health and similar EU research programs. Through this conference ENBEL aims at help strengthening the health argument for climate action.

## Links

-  [http://enbel2023.se](http://enbel2023.se)
