---
title: "European Launch of the 2023 Lancet Countdown Report"
author: "Lancet Countdown"
date: 2023-11-29
categories: [conference, online, free, 2023]
---

## Description

The Lancet Countdown: Tracking Progress on Health and Climate Change is an international research collaboration that brings together 114 leading experts to monitor how the world's changing climate is impacting on public health. Every year, the Lancet Countdown publishes a report that harnesses the latest global data to make clear how climate change is affecting our health, the consequences of delayed action and the health benefits of a robust response.

The 2023 Report will be launched ahead of the 28th UN Conference of the Parties of the UNFCC (COP28), which will -- for the first time -- feature health as a key theme, with an official Health Day and climate-health ministerial. Our report contributes to the evidence need to inform the negotiations, and deliver truly health-protecting climate change action.

## Links

-   <https://event.eu.on24.com/wcc/r/8000058838/A6C84071F91ECCD8CE9C737B4D79A148>

-   <https://www.lancetcountdown.org/2023-report/>
