---
title: "Modeling of infectious diseases course"
author: "Institut Pasteur"
date: 2024-05-13
categories: [course, in person, free, 2024]
---

## Description

Mathematical modeling has become an essential tool for the study of infectious disease epidemics, making it possible to better characterize the complex transmission dynamics inherent to the spread of pathogens in human populations. Mathematical models are now commonly used to address a variety of questions that can inform policy making, for example, the optimal allocation of control measures, the planning and evaluation of vaccination programmes, nowcasting and forecasting of epidemics and real-time risk assessment during epidemics.

This one-week course aims at introducing the main modeling techniques and applications to students and professionals in science, medicine and public health. The main learning objectives of the course are that participants:

1\) understand the key theoretical concepts and techniques of infectious disease modeling;

2\) can read modeling papers, understand the strengths and limits of modeling approaches; and are able to use modeling results in their own research and effectively interact with modelers. To achieve these objectives, the course will be partitioned in three types of sessions: a set of lectures introducing key theoretical concepts and techniques, a seminar series illustrating how these concepts are being used to tackle major Public Health challenges, and practical sessions during which participants will learn to implement, run and use models.

A Masters or BSc degree is required, as well as basic math knowledge (high school-level knowledge on derivatives, basics of probabilities and statistics).

## Links

-   <https://www.pasteur.fr/en/education/programs-and-courses/pasteur-courses?id_cours=32329>
