---
title: "Age standardized Covid-19 mortality rates for Brazil"
date: "2023-11-06"
categories: [covid19, tidyrates]
---

## Packages
```{r}
library(tidyverse)
```


## Data

```{r}
date_format <- "%d%m%Y"

cols_spec <- cols(
  ORIGEM = col_double(),
  TIPOBITO = col_double(),
  DTOBITO = col_date(format = date_format),
  HORAOBITO = col_character(),
  NATURAL = col_character(),
  CODMUNNATU = col_double(),
  DTNASC = col_date(format = date_format),
  IDADE = col_double(),
  SEXO = col_double(),
  RACACOR = col_double(),
  ESTCIV = col_double(),
  ESC = col_double(),
  ESC2010 = col_double(),
  SERIESCFAL = col_double(),
  OCUP = col_character(),
  CODMUNRES = col_double(),
  LOCOCOR = col_double(),
  CODESTAB = col_character(),
  ESTABDESCR = col_character(),
  CODMUNOCOR = col_double(),
  IDADEMAE = col_double(),
  ESCMAE = col_double(),
  ESCMAE2010 = col_double(),
  SERIESCMAE = col_double(),
  OCUPMAE = col_double(),
  QTDFILVIVO = col_character(),
  QTDFILMORT = col_character(),
  GRAVIDEZ = col_double(),
  SEMAGESTAC = col_double(),
  GESTACAO = col_double(),
  PARTO = col_double(),
  OBITOPARTO = col_double(),
  PESO = col_character(),
  TPMORTEOCO = col_double(),
  OBITOGRAV = col_double(),
  OBITOPUERP = col_double(),
  ASSISTMED = col_double(),
  EXAME = col_character(),
  CIRURGIA = col_character(),
  NECROPSIA = col_double(),
  LINHAA = col_character(),
  LINHAB = col_character(),
  LINHAC = col_character(),
  LINHAD = col_character(),
  LINHAII = col_character(),
  CAUSABAS = col_character(),
  CB_PRE = col_character(),
  COMUNSVOIM = col_character(),
  DTATESTADO = col_date(format = date_format),
  CIRCOBITO = col_double(),
  ACIDTRAB = col_double(),
  FONTE = col_double(),
  NUMEROLOTE = col_double(),
  TPPOS = col_character(),
  DTINVESTIG = col_date(format = date_format),
  CAUSABAS_O = col_character(),
  DTCADASTRO = col_date(format = date_format),
  ATESTANTE = col_double(),
  STCODIFICA = col_character(),
  CODIFICADO = col_character(),
  VERSAOSIST = col_number(),
  VERSAOSCB = col_number(),
  FONTEINV = col_double(),
  DTRECEBIM = col_date(format = date_format),
  ATESTADO = col_character(),
  DTRECORIGA = col_date(format = date_format),
  CAUSAMAT = col_character(),
  ESCMAEAGR1 = col_character(),
  ESCFALAGR1 = col_character(),
  STDOEPIDEM = col_double(),
  STDONOVA = col_double(),
  DIFDATA = col_character(),
  NUDIASOBCO = col_double(),
  NUDIASOBIN = col_character(),
  DTCADINV = col_date(format = date_format),
  TPOBITOCOR = col_double(),
  DTCONINV = col_date(format = date_format),
  FONTES = col_character(),
  TPRESGINFO = col_double(),
  TPNIVELINV = col_character(),
  NUDIASINF = col_character(),
  DTCADINF = col_date(format = date_format),
  MORTEPARTO = col_double(),
  DTCONCASO = col_date(format = date_format),
  FONTESINF = col_character(),
  ALTCAUSA = col_double(),
  CONTADOR = col_double()
)
```


```{r}
sim19 <- readr::read_csv2(file = "../../covidbr/Mortalidade_Geral_2019.csv", col_types = cols_spec)
sim20 <- readr::read_csv2(file = "../../covidbr/Mortalidade_Geral_2020.csv", col_types = cols_spec)
sim21 <- readr::read_csv2(file = "../../covidbr/Mortalidade_Geral_2021.csv", col_types = cols_spec)
sim22 <- readr::read_csv2(file = "../../covidbr/DO22OPEN.csv", col_types = cols_spec)
sim23 <- readr::read_csv2(file = "../../covidbr/DO23OPEN.csv", col_types = cols_spec)

covid <- bind_rows(sim19, sim20, sim21, sim22, sim23) %>%
  filter(CAUSABAS == "B342") %>%
  filter(DTOBITO >= as.Date("2019-01-01") & DTOBITO <= as.Date("2022-12-31")) %>%
  select(DTOBITO, DTNASC, CODMUNRES)

rm(cols_spec, sim19, sim20, sim21, sim22, sim23)
```

```{r}
covid2 <- covid %>%
  na.omit() %>%
  mutate(
    age = year(as.period(interval(start = DTNASC, end = DTOBITO))),
    age_group = case_when(
      age <= 4 ~ "From 0 to 4 years",
      age >= 5 & age <= 9 ~ "	From 5 to 9 years",
      age >= 10 & age <= 14 ~ "From 10 to 14 years",
      age >= 15 & age <= 19 ~ "From 15 to 19 years",
      age >= 20 & age <= 24 ~ "From 20 to 24 years",
      age >= 25 & age <= 29 ~ "From 25 to 29 years",
      age >= 30 & age <= 34 ~ "From 30 to 34 years",
      age >= 30 & age <= 34 ~ "From 30 to 34 years",
      age >= 35 & age <= 39 ~ "From 35 to 39 years",
      age >= 40 & age <= 44 ~ "From 40 to 44 years",
      age >= 45 & age <= 49 ~ "From 45 to 49 years",
      age >= 50 & age <= 54 ~ "From 50 to 54 years",
      age >= 55 & age <= 59 ~ "From 55 to 59 years",
      age >= 60 & age <= 64 ~ "From 60 to 64 years",
      age >= 65 & age <= 69 ~ "From 65 to 69 years",
      age >= 70 & age <= 74 ~ "From 70 to 74 years",
      age >= 75 & age <= 79 ~ "From 75 to 79 years",
      age >= 80 ~ "From 80 years or more"
    )
  )
```

```{r}
covid2 %>%
  group_by(date = DTOBITO, age_group) %>%
  summarise(freq = n()) %>%
  ungroup() %>%
  ggplot(aes(x = date, y = freq)) +
  geom_line() +
  facet_wrap(~age_group) +
  theme_bw()
```


```{r}
covid_agg <- covid2 %>%
  group_by(code_muni = CODMUNRES, age_group) %>%
  summarise(freq = n()) %>%
  ungroup()
```

```{r}
mun_uf <- brpop::mun_pop() %>%
  filter(year %in% 2019:2023) %>%
  rename(population = pop) %>%
  filter(age_group != "Total") %>%
  mutate(year = as.character(year))
```

Repetir 2021 para 2022.

```{r}
seer2 <- tidyrates::seer_std_pop %>%
  mutate(age_group = case_when(
    age_group == "0-4" ~ "From 0 to 4 years",
    age_group == "5-9" ~ "From 5 to 9 years",
    age_group == "10-14" ~ "From 10 to 14 years",
    age_group == "15-19" ~ "From 15 to 19 years",
    age_group == "20-24" ~ "From 20 to 24 years",
    age_group == "25-29" ~ "From 25 to 29 years",
    age_group == "30-34" ~ "From 30 to 34 years",
    age_group == "35-39" ~ "From 35 to 39 years",
    age_group == "40-44" ~ "From 40 to 44 years",
    age_group == "45-49" ~ "From 45 to 49 years",
    age_group == "50-54" ~ "From 50 to 54 years",
    age_group == "55-59" ~ "From 55 to 59 years",
    age_group == "60-64" ~ "From 60 to 64 years",
    age_group == "65-69" ~ "From 65 to 69 years",
    age_group == "70-74" ~ "From 70 to 74 years",
    age_group == "75-79" ~ "From 75 to 79 years",
    age_group == "80-84" ~ "From 80 years or more",
    age_group == "85-89" ~ "From 80 years or more",
    age_group == "90-94" ~ "From 80 years or more",
    age_group == "95-99" ~ "From 80 years or more",
    age_group == "100+" ~ "From 80 years or more",
    .default = age_group
  )) %>%
  group_by(age_group) %>%
  summarise(population = sum(population)) %>%
  ungroup()
```











