---
title: "What have we learned from Mariana? The importance of names, places and affections"
author:
  - Nadja Araújo
  - Keila Carnavalli
  - Nathalia Barbosa
  - Patricia Barcelos
  - Raphael Saldanha
  - Teresa Neves
  - Vinicius Klein
  - Maria Guimarães
date: 2019-05-16
categories: 
  - Mariana
  - Disaster
bibliography: publications.bib
csl: abnt.csl
---

---
nocite: |
  @araujoWHATHAVEWE2019a
---

## Referência

::: {#refs}
:::

Nomear é uma tarefa ambiciosa. Nomear um objeto ou evento significa reconhecê-lo, distingui-lo e atribuir-lhe importância. Quem nomeia adquire poder sobre aquilo que antes era indescritível. O nome é signo e significado, enviesado em sua origem e em seu uso. Nomear e compreender a complexidade do que ocorreu na cidade de Mariana, suas causas e consequências, representa um desafio para o qual abordagens disciplinares centradas no conhecimento científico são insuficientes. Assim, nossa busca por estudos sobre o que aconteceu em Mariana após o rompimento da Barragem de Fundão em novembro de 2015 deve ser complementada pelas histórias dos moradores daquele lugar, por seus saberes. Reconhecemos que essa abordagem para examinar tal questão seria apenas uma contribuição limitada e, por isso, constitui a condição primária para um exercício interdisciplinar.
